2.4.1
Bib8/sky-exceptions-2-3 pull request #1
Opened 2022-01-29 21:48 UTC by Bib8

2022-01-30 14:53 UTC, madyar997 requested changes

2022-01-30 14:53 UTC, madyar997 commented on src/main/java/sky/pro/skyexceptions23/classes/Employee.java
> +public class Employee extends Person{
Так как мы пишем по архитектуре mvc - лучше назвать package - model или data

2022-01-30 14:53 UTC, madyar997 commented on src/main/java/sky/pro/skyexceptions23/controllers/EmployeeController.java
> +    }
Для чего нужны отдельные методы для работы с Ivanov?)

2022-01-30 14:53 UTC, madyar997 commented on src/main/java/sky/pro/skyexceptions23/services/EmployeeServiceImpl.java
> +            count = i;
не приравнивать к i, а увеличивать сounter на единицу в случае если обьект не null

2022-01-30 14:53 UTC, madyar997 commented on src/main/java/sky/pro/skyexceptions23/services/EmployeeServiceImpl.java
> +        if (empolyeesQTY <= employees.length){
Это условие будет true даже если empolyeesQTY будет равен 0. Лучше увеличивать длину массива если количество элементов в массиве равно длине массива.

2022-01-30 14:53 UTC, madyar997 commented on src/main/java/sky/pro/skyexceptions23/services/EmployeeServiceImpl.java
> +        }  employees[employees.length / 2 + 1] = new Employee(firstName, lastName);
А если по индексу employees.length/2+1 уже есть элемент, мы его потеряем, он перезапишется новым значением. Перед добавлением нужно найти ячейку массива которая пуста.

2022-01-30 14:53 UTC, madyar997 commented on src/main/java/sky/pro/skyexceptions23/services/EmployeeServiceImpl.java
> +        return id;
Если не найден элемент метод вернет null, но не исключение

2022-01-30 14:53 UTC, madyar997 commented on src/main/java/sky/pro/skyexceptions23/services/EmployeeServiceImpl.java
> +                for (int i = 0; i < (employersQTY - id); i++) {
Вот здесь возникнет NullPointerException если такого сотрудника нет в массиве, так как findId вернет id = null

2022-02-04 16:05 UTC, Bib8 commented on src/main/java/sky/pro/skyexceptions23/controllers/EmployeeController.java
> +    }
Не стал убирать свои методы, нужны как template

2022-02-04 16:05 UTC, closed without merging